parameters:
services:

    ddr.symfonyangularrestexample.security.api_key_authenticator:
        class: Net\Dontdrinkandroot\SymfonyAngularRestExample\RestBundle\Security\ApiKeyAuthenticator
        arguments:
            - '@ddr.symfonyangularrestexample.service.user'
            - '@security.http_utils'

    # This is a workaround since Symfony does not handle InsufficientAuthenticationException with a 401 status code when
    # firewall has anonymous enabled.
    # See https://github.com/symfony/symfony/issues/8467
    ddr.symfonyangularrestexample.kernel.listener.exception:
        class: Net\Dontdrinkandroot\SymfonyAngularRestExample\RestBundle\Security\ExceptionListener
        arguments:
            - '@security.context'
            - '@security.authentication.trust_resolver'
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 1000 }