language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --dev
  - bin/console doctrine:schema:create

script:
  - bin/phpcs --standard=psr2 --ignore=*.js ./src
  - bin/phpunit
