language: php

php:
    - 5.5

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install --dev
    - bin/console doctrine:schema:create

script: bin/phpunit -c app/