parameters:
services:

    ddr.symfonyangularrestexample.security.api_key_authenticator:
        class: Dontdrinkandroot\SymfonyAngularRestExample\RestBundle\Security\ApiKeyAuthenticator
        arguments:
            - '@ddr.symfonyangularrestexample.service.user'
