imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'DdrSymfonyAngularRestExampleAngular1Bundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "pdo_sqlite"
        path: "%kernel.root_dir%/../var/data/database.db"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# FOS User Bundle configuration
fos_user:
    db_driver: orm
    user_class: Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Entity\User
    firewall_name: main
    service:
        mailer: fos_user.mailer.noop

braincrafted_bootstrap:
    auto_configure:
        assetic: false

# FOS Rest Bundle configuration
fos_rest:
    serializer:
        groups: ['Default']
    exception:
        codes:
            'Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Exception\NoResultException': 404
    format_listener:
        rules:
            - { path: '^/rest/', priorities: ['json', 'xml'], prefer_extension: true }
            - { path: '^/', stop: true }
    disable_csrf_role: ROLE_REST_API
    view:
        view_response_listener:
            enabled: true

# JMS Serializer Bundle configuration
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "@DdrSymfonyAngularRestExampleBaseBundle/Resources/config/serializer/fos"