fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

ddr_symfony_angular_rest_example_rest:
    prefix: /rest
    type: rest
    resource: "@DdrSymfonyAngularRestExampleRestBundle/Resources/config/routing.yml"

ddr_symfony_angular_rest_example_web:
    resource: "@DdrSymfonyAngularRestExampleWebBundle/Resources/config/routing.yml"
    prefix:   /

ddr_symfony_angular_rest_example_angular1:
    resource: "@DdrSymfonyAngularRestExampleAngular1Bundle/Resources/config/routing.yml"
    prefix:   /angular1/


ddr_symfony_angular_rest_example_angular2:
    resource: "@DdrSymfonyAngularRestExampleAngular2Bundle/Resources/config/routing.yml"
    prefix:   /angular2/
