fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /twig/

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /twig/user/profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /twig/user/reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /twig/user/profile

ddr_symfony_angular_rest_example_rest:
    prefix: /rest
    type: rest
    resource: "@DdrSymfonyAngularRestExampleRestBundle/Resources/config/routing.yml"

ddr_symfony_angular_rest_example_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /angular1/
        permanent: false

ddr_symfony_angular_rest_example_web:
    resource: "@DdrSymfonyAngularRestExampleWebBundle/Resources/config/routing.yml"
    prefix:   /twig/

ddr_symfony_angular_rest_example_angular1:
    resource: "@DdrSymfonyAngularRestExampleAngular1Bundle/Resources/config/routing.yml"
    prefix:   /angular1/

ddr_symfony_angular_rest_example_angular2:
    resource: "@DdrSymfonyAngularRestExampleAngular2Bundle/Resources/config/routing.yml"
    prefix:   /angular2/
