security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        rest:
            pattern: ^/rest
            stateless: true
            simple_preauth:
                authenticator: ddr.symfonyangularrestexample.security.api_key_authenticator

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest/users/createapikey, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest/*, roles: ROLE_USER }
        - { path: .*, roles: ROLE_USER }
