security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        rest:
            pattern: ^/rest
            stateless: true
            http_basic: ~
            simple_preauth:
                authenticator: ddr.symfonyangularrestexample.security.api_key_authenticator
            anonymous: true

        main:
            pattern: ^/twig
            form_login:
                login_path: /twig/login
                check_path: /twig/login_check
                provider: fos_userbundle
                default_target_path: /twig/
            logout:
                path: /twig/logout
                target: /twig/
            anonymous: true

    access_control:
        - { path: ^/twig/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/twig/newsentries/.*/edit$, role: ROLE_USER }
        - { path: ^/twig/newsentries/.*/delete$, role: ROLE_USER }
        - { path: ^/rest/users/createapikey$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest/*, methods: [POST,PUT,DELETE], role: ROLE_USER }
        - { path: ^/rest/users*, role: ROLE_USER }
