Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Entity\BlogPost:
    type: entity
    table: null
    repositoryClass: Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Repository\BlogPostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 63
            nullable: false
        content:
            type: text
            length: 511
            nullable: false
        date:
            type: datetime
            nullable: false
        numComments:
            type: integer
            nullable: false
            options:
                default: 0
    manyToOne:
        author:
            targetEntity: User
            inversedBy: blogPosts
            joinColumn:
                nullable: false
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: blogPost
            cascade: [remove]
    lifecycleCallbacks: {  }
