Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Entity\BlogPost:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        title:
            expose: true
        content:
            expose: true
        date:
            expose: true
        numComments:
            expose: true
        author:
            expose: true