services:

    # Repositories

    ddr.symfonyangularrestexample.repository.user:
        class: Net\Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Repository\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ Net\Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Entity\User ]

    ddr.symfonyangularrestexample.repository.newsentry:
        class: Net\Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Repository\NewsEntryRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ Net\Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Entity\NewsEntry ]

    # Services

    ddr.symfonyangularrestexample.service.newsentry:
        class: Net\Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Service\DoctrineNewsEntryService
        arguments:
            - '@ddr.symfonyangularrestexample.repository.newsentry'

    ddr.symfonyangularrestexample.service.user:
        class: Net\Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Service\DoctrineUserService
        arguments:
            - '@ddr.symfonyangularrestexample.repository.user'