services:

    # Repositories

    ddr.symfonyangularrestexample.repository.user:
        class: Net\Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Repository\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ Net\DontdrinkandrootHoodHero\SymfonyAngularRestExample\BaseBundle\Entity\User ]
