Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Entity\BlogPost:
    properties:
        title:
            - Type:
                type: string
            - NotBlank: ~
            - Length:
                min: 1
                max: 63
        content:
            - Type:
                type: string
            - NotBlank: ~
            - Length:
                min: 1
                max: 511

Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Entity\Comment:
    properties:
        content:
            - Type:
                type: string
            - NotBlank: ~
            - Length:
                min: 1
                max: 255