ddr_symfony_angular_rest_example_rest_user:
    prefix: users
    resource: "@DdrSymfonyAngularRestExampleRestBundle/Controller/UserController.php"
    type: rest
    name_prefix: ddr_example_rest_user_

ddr_symfony_angular_rest_example_rest_blogpost:
    prefix: blogposts
    resource: "@DdrSymfonyAngularRestExampleRestBundle/Controller/BlogPostController.php"
    type: rest
    name_prefix: ddr_example_rest_blogpost_