ddr_symfony_angular_rest_example_rest_user:
    resource: "@DdrSymfonyAngularRestExampleRestBundle/Controller/UserController.php"
    type: rest
    name_prefix: ddr_example_rest_

ddr_symfony_angular_rest_example_rest_blogpost:
    resource: "@DdrSymfonyAngularRestExampleRestBundle/Controller/BlogPostController.php"
    type: rest
    name_prefix: ddr_example_rest_