Net\Dontdrinkandroot\SymfonyAngularRestExample\BaseBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            expose: true
        username:
            type: string
            expose: true
        roles:
            type: array
            expose: true