ddr_example_angular1_homepage:
    path:     /{catchall}
    defaults: { _controller: DdrSymfonyAngularRestExampleAngular1Bundle:Default:index, catchall: '' }
    requirements:
        catchall: ".*"
