Dontdrinkandroot\SymfonyAngularRestExample\RestBundle\Model\UserCredentials:
    exclusion_policy: ALL
    properties:
        username:
            type: string
            expose: true
        password:
            type: string
            expose: true