ddr_example_web_blogpost_edit:
    path:     /blogposts/{id}/edit
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:BlogPost:edit }

ddr_example_web_blogpost_delete:
    path:     /blogposts/{id}/delete
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:BlogPost:delete }

ddr_example_web_blogpost_detail:
    path:     /blogposts/{id}
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:BlogPost:detail }

ddr_example_web_comment_delete:
    path:     /comments/{id}/delete
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:BlogPost:deleteComment }

ddr_example_web_index:
    path:     /
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:Default:index }
