ddr_example_web_blogpost_edit:
    path:     /newsentries/{id}/edit
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:BlogPost:edit }

ddr_example_web_blogpost_delete:
    path:     /newsentries/{id}/delete
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:BlogPost:delete }

ddr_example_web_blogpost_detail:
    path:     /newsentries/{id}
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:BlogPost:detail }

ddr_example_web_index:
    path:     /
    defaults: { _controller: DdrSymfonyAngularRestExampleWebBundle:Default:index }
